# Fly.io configuration file
app = "kalshi-poly-scanner"
primary_region = "sjc"  # San Jose, California

[build]
  builder = "heroku"

[env]
  USE_REAL_API = "true"

[[services]]
  internal_port = 8000
  processes = ["app"]

  [services.http_checks]
    enabled = true
    grace_period = "5s"
    interval = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[[statics]]
  guest_path = "/frontend/dist"
  url_prefix = "/"
